FROM centos:latest

MAINTAINER FOSSEE <pythonsupport@fossee.in>

RUN dnf update -y && yum install epel-release python3-devel git python3-pip vim mariadb-devel  -y

RUN dnf install python3-mod_wsgi httpd gcc make -y 

RUN mkdir -p /Sites/online_test

COPY . /Sites/online_test

RUN pip3 install -r /Sites/online_test/requirements/requirements-production.txt 

COPY docker/Files/000-default.conf /etc/httpd/conf.d

COPY docker/Files/Docker-script.sh /Sites/Docker-script.sh

COPY docker/Files/celeryd /etc/init.d/celeryd

COPY docker/Files/celeryd_default /etc/default/celeryd

COPY docker/docker.env /Sites/online_test/.env

RUN useradd celery && chmod 755 /etc/init.d/celeryd &&  chown root:root /etc/init.d/celeryd && mkdir -p /var/log/celery/ && mkdir -p /var/run/celery/ && chown -R celery. /var/log/celery/ && chown -R celery. /var/run/celery/
EXPOSE 80

WORKDIR /Sites/online_test

RUN mkdir -p yaksh_data/output yaksh_data/data

CMD [ "/bin/bash" , "/Sites/Docker-script.sh" ] 
